### DISCUSSION TITLE
Доступ к объектам для управления бризером

### DISCUSSION THREAD

**Discussion by tms320** [TionAPI/HA-tion#105] [Q&A] [answered]
## Общая информация
  * **версия Home Assistant**: 2022.8.1
  * **способ установки Home Assistant**:
    [ ] venv
    [x] Docker (HA supervised)
    [ ] Home Assistant OS
 * **версия компонента**: 3.0.2
 * **модель бризера**: 4S 
 * **версия python-модуля**: 

## Краткое описание
Как я понял, управление бризером осуществляется с помощью этих объектов (обведены красным):
![image](https://user-images.githubusercontent.com/24802646/183128046-a97c0a24-12b8-4e74-a350-8ae0170c8123.png)
Остальные объекты - только "для чтения".
Через объект "fan.tion_de_a7_3b_cf_5f_a5_fan_speed" можно включать/выключать бризер (вентилятор).
Объект "climate.tion_breezer" является "составным", т.е. внутри него есть объекты для изменения режима работы, скорости вентилятора, задания температуры. Но эти объекты доступны только из GUI (через диалог, открывающийся при клике на объекте "climate.tion_breezer").
Вопрос: а как получить доступ к этим "внутренним" объектам, например, из скриптов? Или как, например, создать на панели графический контрол для изменения задания температуры или скорости вентилятора напрямую, а не через клик по объекту "climate.tion_breezer"?

**Comment by IATkachenko** [comment]
Это -- не совсем issue, утащил в дискуссии... Сейчас расскажу и покажу )

**Comment by IATkachenko** [comment, marked as answer]
Ну по порядку.
Все, что вы делаете в интерфейсе -- это карточки интерфейса. Как они дают отобразить тот или иной параметр, так и будет.
У меня сделано так:
![изображение](https://user-images.githubusercontent.com/17473830/183145380-cb9bedf5-ec62-45ba-b712-9d3f7ed22f89.png)
Это -- набор из 7 карточек:
  * vertical-stack -- как объединяющая
    * первый столбец
      * button для `climate.tion_breezer`
      * thermostat для `climate.tion_breezer`
      * gaude для умной розетки, в которую воткнут бризер
    * второй столбец
      * buttnon для автоматизации включающей турборежим
      * custom:mushroom-fan-card для `fan`
      * entity для `select.tion_breezer_air_mode`

Кроме "грибной" карты -- все стандартное. Грибная вот отсюда https://github.com/piitaya/lovelace-mushroom

Супруга захотела так:
![изображение](https://user-images.githubusercontent.com/17473830/183145473-fdc56d46-7f31-443b-94d8-12e40f51b739.png)
Это -- одна карточка `custom:simple-thermostat` из https://github.com/nervetattoo/simple-thermostat

Ну а доступ в скриптах -- как обычно в HA, через `device` и `service` (почитайте как вообще это делается. Как я понимаю, у вас в этой области не очень много опыта).
Вот так, например, выглядит (примерно) включение турбо режима через скрипт:
```yaml
alias: Tion турбо режим
sequence:  
      - condition: not
        conditions:
          - condition: state
            entity_id: climate.tion_breezer
            state: recirculation
            attribute: air_mode
      - device_id: 25e0a70ae5a84822a1465e16372ff090
        domain: climate
        entity_id: climate.tion_breezer
        type: set_preset_mode
        preset_mode: boost
mode: single
icon: mdi:car-turbocharger

```
