### DISCUSSION TITLE
Делимся автоматизациями

### DISCUSSION THREAD

**Discussion by IATkachenko** [TionAPI/HA-tion#73] [Show and tell]
Предлагаю в этой ветке делиться с сообществом тем, как используется бризер (и компонент) в умном доме.

Поскольку HA умеет строить автоматизации на основе устройств, в конфигах они сохраняются в виде ID и пользоваться через copy-paste рецептами нельзя, но если убрать device_id и вставить автоматизацию в редактор -- можно выбрать нужные устройства в своей инсталляции.
Поэтому в конфигах убирайте, пожалуйста, поле device_id (да и вообще все поля, которые ID) -- это позволит без лишних проблем применить вашу автоматизацию.
А для форматирования используйте **\`\`\`yaml** в начале и **\`\`\`** в конце

**Comment by IATkachenko** [comment]
Ну и начну :)
Переводим бризер в ночнйо режим по событию от [SleepAsAndroid](https://github.com/IATkachenko/HA-SleepAsAndroid)
```yaml
alias: Тихий режим бризера ночью
description: ''
mode: single
trigger:
  - platform: device
    domain: sleep_as_android
    type: sleep_tracking_started
    id: start
  - platform: device
    domain: sleep_as_android
    type: sleep_tracking_stopped
    id: stop
condition:
  - condition: state
    entity_id: person.igor
    state: home
action:
  - choose:
      - conditions:
          - condition: trigger
            id: stop
          - condition: device            
            domain: climate
            entity_id: climate.tion_breezer
            type: is_preset_mode
            preset_mode: sleep
        sequence:
          - domain: climate
            entity_id: climate.tion_breezer
            type: set_preset_mode
            preset_mode: none
      - conditions:
          - condition: trigger
            id: start
          - condition: not
            conditions:
              - condition: device                
                domain: climate
                entity_id: climate.tion_breezer
                type: is_hvac_mode
                hvac_mode: 'off'
        sequence:
          - domain: climate
            entity_id: climate.tion_breezer
            type: set_preset_mode
            preset_mode: sleep
    default: []
```

**Comment by IATkachenko** [comment]
Следим за уровнем Co2 в комнате при помощи MHZ-19B и подстраиваем скорость вентилятора в зависимости от уровня:
* <450 1 скорость
* 450-550 -- 2ая
* больше 550 -- 4ая
```yaml
alias: Контроль Co2
description: ''
mode: single
trigger:
  - platform: time_pattern
    minutes: /10
  - platform: state
    entity_id: climate.tion_breezer
    attribute: preset_mode
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.tion_breezer
        state: 'off'
  - condition: not
    conditions:
      - condition: device
        domain: climate
        entity_id: climate.tion_breezer
        type: is_preset_mode
        preset_mode: boost
  - condition: not
    conditions:
      - condition: state
        entity_id: select.tion_breezer_air_mode
        state: recirculation
action:
  - choose:
      - conditions:
          - type: is_carbon_dioxide
            condition: device
            entity_id: sensor.livingroomsensorsbed_mhz19b_carbondioxide
            domain: sensor
            below: 450
        sequence:
          - service: climate.set_fan_mode
            data:
              fan_mode: '1'
            target:
      - conditions:
          - type: is_carbon_dioxide
            condition: device
            entity_id: sensor.livingroomsensorsbed_mhz19b_carbondioxide
            domain: sensor
            above: 450
            below: 550
        sequence:
          - service: climate.set_fan_mode
            target:
            data:
              fan_mode: '2'
    default:
      - service: climate.set_fan_mode
        target:
        data:
          fan_mode: '4'


```

**Reply by fishenebelny** [reply]
У меня тоже самое. Только проверка воздуха каждые 5 минут и уровни CO2 другие.

**Comment by fishenebelny** [comment]
По автоматизации было бы интересно посмотреть какую-то автоматическую регулировку температуры. Она не сильно нужна, но вот в моменты когда дома отключают отопление или меняют температуру было бы интересно как-то коррелировать.
Допустим когда самая жара - подогревать воздух максимум до 7 градусов. Когда батареи отключены - температура подогрева, допустим до максимума необходимого.
Но пока в голове не сложилась концепция как это сделать. Только идея есть.

**Reply by IATkachenko** [reply]
> По автоматизации было бы интересно посмотреть какую-то автоматическую регулировку температуры. Она не сильно нужна, но вот в моменты когда дома отключают отопление или меняют температуру было бы интересно как-то коррелировать. Допустим когда самая жара - подогревать воздух максимум до 7 градусов. Когда батареи отключены - температура подогрева, допустим до максимума необходимого. Но пока в голове не сложилась концепция как это сделать. Только идея есть.

Это -- не самая лучшая идея. Бризер не должен греть воздух в комнате, он на это не рассчитан (и, как не однократно говорилось самими Тионами: "не климатическое оборудование"). Решать через него проблему регулировки отопления -- плохой способ использования. Хуже только кондиционер включать, по моему. А еще, например, мне как-то не комфортно когда на меня холодный воздухом дует. Даже если батарея работает на полную.

Но если очень хочется, то на батарею можно повесить датчик температуры и ориентироваться на его показания.

**Reply by fishenebelny** [reply]
Понятно, что Тион не для отопления. Больше для создания более комфортной температуры. Скажем когда батареи жарят наполную приятно когда оттуда холодный воздух дует и суммарно не такая жара дома. Или в межсезонье, когда батареи отключают, но на улице еще не так тепло как хотелось бы. И тогда воздух подогреть бы, чтобы не совсем холодно было.
Идея с датчиком на батарею интересная. Может попробую.

**Reply by edo1** [reply]
> Это -- не самая лучшая идея. Бризер не должен греть воздух в комнате, он на это не рассчитан (и, как не однократно говорилось самими Тионами: "не климатическое оборудование")

и что будет, если регулярно использовать его с максимальной температурой?

> Хуже только кондиционер включать, по моему

хм, а с кондиционером-то что не так?

> А еще, например, мне как-то не комфортно когда на меня холодный воздухом дует

так бризер должен располагаться так, чтобы не дуть непосредственно на людей, разве нет?

**Comment by plesetsk** [comment]
Включение вентиляции или обогрева по показаниям датчика senseair и наружной температуры от самого бризера.
Дополнительно заведен переключатель для ночного состояния дома (**input_boolean.night_time**). Ночью скорость бризера на 1 меньше дневной. Подогрев включается только ночью. Внутри каждой опции выполняется проверка установлен ли уже соответствующий режим работы, чтобы лишний раз не дергать бризер.

```
alias: Breezer
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.senseair_co2_value
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.senseair_co2_value
        above: "600"
    then:
      - service: climate.set_hvac_mode
        data: >-
          {% if int(states('sensor.tion_breezer_input_temperature')) > 17 or
          states('input_boolean.night_time') == 'off' %}
            {"hvac_mode": "fan_only" }
          {% else %}
            {"hvac_mode": "heat" }
          {% endif %}
        target:
          entity_id: climate.tion_breezer
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.senseair_co2_value
                above: "600"
                below: "800"
            sequence:
              - if:
                  - condition: template
                    value_template: >-
                      {{int(states('sensor.tion_breezer_current_fan_speed')) !=
                      (3 - int(states('input_boolean.night_time') == 'on'))}}
                then:
                  - service: climate.set_fan_mode
                    data:
                      fan_mode: "{{3 - int(states('input_boolean.night_time') == 'on')}}"
                    target:
                      entity_id: climate.tion_breezer
          - conditions:
              - condition: numeric_state
                entity_id: sensor.senseair_co2_value
                above: "800"
                below: "1100"
            sequence:
              - if:
                  - condition: template
                    value_template: >-
                      {{int(states('sensor.tion_breezer_current_fan_speed')) !=
                      (4 - int(states('input_boolean.night_time') == 'on'))}}
                then:
                  - service: climate.set_fan_mode
                    data:
                      fan_mode: "{{4 - int(states('input_boolean.night_time') == 'on')}}"
                    target:
                      entity_id: climate.tion_breezer
          - conditions:
              - condition: numeric_state
                entity_id: sensor.senseair_co2_value
                above: "1100"
            sequence:
              - if:
                  - condition: template
                    value_template: >-
                      {{int(states('sensor.tion_breezer_current_fan_speed')) !=
                      (5 - int(states('input_boolean.night_time') == 'on'))}}
                then:
                  - service: climate.set_fan_mode
                    data:
                      fan_mode: "{{5 - int(states('input_boolean.night_time') == 'on')}}"
                    target:
                      entity_id: climate.tion_breezer
        default: []
    else:
      - device_id: 9d5310baf943536bc439d16c71e79435
        domain: climate
        entity_id: climate.tion_breezer
        type: set_hvac_mode
        hvac_mode: "off"
mode: restart
```
