### ISSUE TITLE
Не работает модуль TION в Home Assistant

### ISSUE THREAD

**Issue by shan197513** [TionAPI/HA-tion#1]
Hi. Сделал все как в описании, но не вижу бризер в HA. Что не так?

**Comment by IATkachenko** [comment]
Включите, пожалуйста, отладку в configuration.yaml и пришлите лог homeassist.log c момента перезапуска.

Включить отладку можно добавив вот такие строки в configuration.yaml
```yaml
logger:
  default: warning
  logs:
    custom_components.tion.climate: debug
    s3: debug
    tion: debug
    tion.s3: debug
```
