### ISSUE TITLE
Ошибка с сопряжение с tion lite

### ISSUE THREAD

**Issue by foxoskol** [TionAPI/HA-tion#26]
Здравствуйте! Релиз последний, при попытке провести сопряжение, вываливается сразу же в ошибку 
![Безымянный](https://user-images.githubusercontent.com/71713159/102206429-a8770900-3edd-11eb-9181-e8936aead1da.jpg)
 В логах:
2020-12-15 13:55:57 ERROR (MainThread) [custom_components.tion.config_flow] Cannot pair and get data. Result is {}, error: 'model'

**Comment by IATkachenko** [comment]
А можно полные логи с включенной отладкой?
configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    custom_components.tion: debug
    tion_btle.tion: debug
    tion_btle.lite: debug
```
